export const GENERATED_READ_SKIP_IDS = [
  'getConfig',
  'getSystemTime',
  'getFriends',
  'getUser',
  'getUserByName',
  'getGroup',
  'getGroupAnnouncements',
  'getGroupCalendarEvents',
  'getGroupNextCalendarEvent',
  'getGroupCalendarEvent',
  'discoverCalendarEvents',
  'searchCalendarEvents',
  'getWorld',
];

export const GENERATED_WRITE_SKIP_IDS = [
  'createInstance',
  'boop',
  'createGroupInvite',
  'friend',
  'inviteMyselfTo',
  'inviteUser',
  'createGroupAnnouncement',
  'deleteGroupAnnouncement',
  'createGroupCalendarEvent',
  'updateGroupCalendarEvent',
  'deleteGroupCalendarEvent',
  'followGroupCalendarEvent',
  'updateUser',
];
